version: 0.0
os: windows
files:
  - source: \
    destination: C:\Users\Administrator\Downloads\
file_exists_behavior: OVERWRITE
hooks: 
 BeforeInstall: 
 - location: \before-install.bat 
   timeout: 900
